### ISSUE TITLE
Sebagai user, saya ingin dapat menambahkan foto kejadian pada detail kejadian kecelakaan sehingga tim penyelamat memiliki referensi awal kejadian secara visual

### ISSUE THREAD

**Issue by arifrhakim** [reza-id/osg3-kelompok-8#5]
Pada saat menyimpan detail, user dapat melampirkan foto kejadian untuk menggambarkan kondisi kecelakaan secara visual

**Comment by wiliarko** [comment]
sepertinya tidak bisa dilakukan karena fasilitas api hanya sebatas read

**Comment by arifrhakim** [comment]
Iya Om. Kirain bisa
